# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: cdk-execution-role.yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.10
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
    - id: ruff
      args: [ "check", "--select", "I", "--fix" ]
      files: "^api/"
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
-   repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.85.0
    hooks:
    -   id: cfn-lint
        files: cdk-execution-role.yaml
