Resources:
  HelloWorldFunctionServiceRole8E0BD458:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: PythonCdkSamStack/HelloWorldFunction/ServiceRole/Resource
  HelloWorldFunctionB2AB6E79:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 342620f0be0a0e8556dbb05dd35083d270fa7b3598500bab20fead5f84353e5a.zip
      Handler: handler.lambda_handler
      Role:
        Fn::GetAtt:
          - HelloWorldFunctionServiceRole8E0BD458
          - Arn
      Runtime: python3.9
    DependsOn:
      - HelloWorldFunctionServiceRole8E0BD458
    Metadata:
      aws:cdk:path: PythonCdkSamStack/HelloWorldFunction/Resource
      aws:asset:path: /Users/neil/Development/Projects/python-cdk-sam/cdk.out/asset.342620f0be0a0e8556dbb05dd35083d270fa7b3598500bab20fead5f84353e5a
      aws:asset:is-bundled: true
      aws:asset:property: Code
  EndpointEEF1FD8F:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Endpoint
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: PythonCdkSamStack/Endpoint/Resource
  EndpointDefaultStage0AD21F27:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: EndpointEEF1FD8F
      AutoDeploy: true
      StageName: $default
    Metadata:
      aws:cdk:path: PythonCdkSamStack/Endpoint/DefaultStage/Resource
  EndpointANYproxyLambdaIntegration7CB84531:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: EndpointEEF1FD8F
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - HelloWorldFunctionB2AB6E79
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: PythonCdkSamStack/Endpoint/ANY--{proxy+}/LambdaIntegration/Resource
  EndpointANYproxyLambdaIntegrationPermission2E8CC96E:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloWorldFunctionB2AB6E79
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /*/*/{proxy+}
    Metadata:
      aws:cdk:path: PythonCdkSamStack/Endpoint/ANY--{proxy+}/LambdaIntegration-Permission
  EndpointANYproxyBD666A87:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      RouteKey: ANY /{proxy+}
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: EndpointANYproxyLambdaIntegration7CB84531
    Metadata:
      aws:cdk:path: PythonCdkSamStack/Endpoint/ANY--{proxy+}/Resource
  HelloWorldApiUrl980457D2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /hello-world/url
      Type: String
      Value:
        Fn::Join:
          - ""
          - - https://
            - Ref: EndpointEEF1FD8F
            - .execute-api.
            - Ref: AWS::Region
            - "."
            - Ref: AWS::URLSuffix
            - /
    Metadata:
      aws:cdk:path: PythonCdkSamStack/HelloWorldApiUrl/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/12QwW6DMAyGn4V7SDeQNu22Fmnabog+QOVCoC4kQbEZqqK8+5RQLjt9/pM/tv8U8vW9lL7IYKW87cZ8wqv0Z4Z2FLDSxSNo6Rs7KVH1JjIIKi9ApJjkMUJQKU9LOyo+ASkxgb52IH3Vm6/FtIzWxKe1chqJ0JogYMYBWK3w+C2k/2aejzNGU0SUZ4YhDdyKeNTYhbfqx7AaHOyN/8nkC4JIxxgOzVCDA61YubTGLkIQjSK7uFaJFCOOQjOkHvtF1ZvKmg45rV3kMM03kC/Z5/O3DpFb4Hx+8M2ap6VOYs8fxKYPpfyQb9mdEHO3GEatZLPxD3ykPyCIAQAA
    Metadata:
      aws:cdk:path: PythonCdkSamStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-3
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-3
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-4
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
      - Fn::Equals:
          - Ref: AWS::Region
          - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
