name: CDK

permissions:
  write-all

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup CDK Python Environment
      uses: ./.github/actions/setup-env

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@main # Or a specific version
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: eu-west-1

    - name: CDK Synth
      run: |
        uv sync --frozen --all-packages --dev
        cd cdk
        uv run cdk synth

    - name: Run tests
      run: |
        uv run pytest

    - name: Build docker image
      run: |
        docker build --platform linux/amd64 --provenance=false  -f api/Dockerfile . -t ghcr.io/valken/hello-api:latest

    - name: Push docker image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u valken --password-stdin
        docker push ghcr.io/valken/hello-api:latest
